import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import InvoiceProvider from "@/context/invoice";
import CreateModalProvider from "@/context/modals/createModal";
import ThemeProvider from "@/context/Theme";
import { leagueSpartan } from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //
  return (
    <html lang='en' className={`${leagueSpartan.variable}`}>
      <body className='overflow-hidden'>
        <ThemeProvider>
          <div
            className={`font-lSpartan flex flex-col lg:flex-row min-h-[600px] h-screen overflow-hidden`}
          >
            <Sidebar />
            <InvoiceProvider>
              <CreateModalProvider>{children}</CreateModalProvider>
            </InvoiceProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
